# Generated by Django 5.0 on 2023-12-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_app', '0002_rename_address_commercialproperty_address1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialproperty',
            name='address1',
        ),
        migrations.AddField(
            model_name='commercialproperty',
            name='address01',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
